config/routes.rb
Reply::Application.routes.draw do
  get "users/new"

  root              to: 'static_pages#home'
  match '/signup',  to: 'users#new'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }

  attr_accessible :name, :email, :password, :password_confirmation
  validates :name, presence: true, length: { maximum: 30 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.haml
%header{ class: "navbar navbar-fixed-top navbar-inverse" }
  %div{ class: "navbar-inner" }
    %div{ class: "container" } 
      = link_to "Reply", '#', id: "logo" 
      %nav
        %ul{ class: "nav pull-right" }
          %li= link_to "Home", root_path 
          %li= link_to "Help", help_path
          %li= link_to "About", about_path
          %li= link_to "Sign in", '#'

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title Reply
    = stylesheet_link_tag    "application", :media => "all" 
    = javascript_include_tag "application" 
    = csrf_meta_tags 

  %body
    = render 'layouts/header'

    %div{ class: "container"}
      = yield

app/views/static_pages/about.html.haml
%h1 About
%p About this app

app/views/static_pages/help.html.haml
%h1 Help
%p Any questions?

app/views/static_pages/home.html.haml
%div{ class: "center hero-unit" }
  %h1 Reply
  %h2 Answer all the messages!

  = link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary"

app/views/users/new.html.haml
%h1 Sign up
%p Find me in app/views/users/new.html.haml